version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: hello-nestjs-mysql
    restart: always
    env_file: 
      - .env
      - .env.production
    ports:
      - '${MYSQL_PORT}:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    volumes:
      - ./docs/sample/mysql/:/var/lib/mysql/ # ./docs/sample/mysql/路径可以替换成自己的路径
      - ./sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本
    networks:
      - hello_nestjs

  redis:
    image: redis:alpine
    container_name: hello-nestjs-redis
    restart: always
    env_file: 
      - .env
      - .env.production
    ports:
      - '${REDIS_PORT}:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - hello_nestjs

  hello-nestjs-server:
    # build: 从当前路径构建镜像
    build: .
    image: steinwei/hello-nestjs-server
    container_name: hello-nestjs-server
    restart: always
    env_file: 
      - .env
      - .env.production
    ports:
      - '7001:7001'
    # 当前服务启动之前先要把depends_on指定的服务启动起来才行
    depends_on:
      - mysql
      - redis
    networks:
      - hello_nestjs

networks:
  hello_nestjs:
    name: hello_nestjs